[package]
name = "openm44"
version = "0.1.0"
authors = ["Aaron Power <theaaronepower@gmail.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_yaml = "0.7"
ggez = "0.3"
lazy_static = "0.2"
rand = "0.3"

[dependencies.yaml-merge-keys]
version = "0.2"
features = ["serde_yaml"]
